name: face_rec
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dropdown_button2: ^1.2.0
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.2+1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  image_picker: ^0.8.4+10
  image_picker_for_web: ^2.1.6
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  kt_dart: ^0.10.0
  rxdart: ^0.27.3
  sa3_liquid: ^1.0.1
  settings_ui: ^2.0.2
  syncfusion_flutter_charts: ^19.4.54
  syncfusion_flutter_datagrid: ^19.4.54
  uuid: ^3.0.6

dev_dependencies:
  auto_route_generator: ^3.2.3
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  injectable_generator: ^1.5.1
  json_serializable: ^6.1.4
  linter: ^1.15.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/can-dynamic-color.png
    - assets/images/file-dynamic-gradient.png
    - assets/images/folder-dynamic-premium.png
    - assets/images/text-dynamic-color.png
    #- images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
