// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKVp1lzg6C6STzzoERcIaJIgrfeI4ruAY',
    appId: '1:635142943228:web:455289f1a30771357c0279',
    messagingSenderId: '635142943228',
    projectId: 'face-recognition-project-90dc7',
    authDomain: 'face-recognition-project-90dc7.firebaseapp.com',
    databaseURL: 'https://face-recognition-project-90dc7-default-rtdb.firebaseio.com',
    storageBucket: 'face-recognition-project-90dc7.appspot.com',
    measurementId: 'G-R24YJ4L16G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm77DBMg9GknTDrsyYOAFlWrdLbwktzm4',
    appId: '1:635142943228:android:2fa3f7edfe3300cb7c0279',
    messagingSenderId: '635142943228',
    projectId: 'face-recognition-project-90dc7',
    databaseURL: 'https://face-recognition-project-90dc7-default-rtdb.firebaseio.com',
    storageBucket: 'face-recognition-project-90dc7.appspot.com',
  );
}
